sudo: required
language: python

cache: pip

services:
  - docker

env:
  matrix:
    - MOLECULE_DISTRO: 18.04
    - MOLECULE_DISTRO: 16.04

addons:
  apt:
    packages:
      - docker-ce=5:18.09.0~3-0~ubuntu*

install:
  - pip install -r requirements.txt

script:
  - molecule test

notifications:
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/
    on_pull_requests: false
    on_success: always
    on_failure: never
    on_start: never
    on_cancel: never
    on_error: never
