---

- name: install docker | Install dependencies if necessary.
  apt:
    name: "{{ docker_required_packages }}"
    state: present
    update_cache: true
    cache_valid_time: "{{ docker_apt_cache_valid_time }}"

- name: install docker | Add Docker official GPG key.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key

- name: install docker | Ensure curl is present (on older systems without SNI).
  package: name=curl state=present
  when: add_repository_key is failed

- name: install docker | Add Docker apt key (alternative for older systems without SNI).
  shell: "curl -sSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
  args:
    warn: false
  when: add_repository_key is failed

- name: install docker | Add the APT Docker repository.
  apt_repository:
    repo: "{{ docker_apt_repo }}"
    state: present
    mode: "644"
    update_cache: true

- name: install docker | Install docker package.
  apt:
    name: "{{ docker_pkg_name }}"
    state: present
    update_cache: true
    cache_valid_time: "{{ docker_apt_cache_valid_time }}"
  notify:
    - Start Docker
