---

# Will create users if they dont exist
- name: Add the Docker adminstrators to Docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  become: true
  with_items: "{{ docker_group_members }}"
  register: docker_add_to_group
