---

- name: Reload Daemon Restart
  systemd:
    name: docker
    daemon_reload: true
    state: restarted

- name: Restart Docker
  service:
    name: docker
    state: restarted

- name: Start Docker
  service:
    name: docker
    state: started
