---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml
platforms:
  - name: instance
    image: thomasjpfan/ubuntu-python-systemd:18.04-py3
    hostname: ansible-local
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init --log-target=journal 3>&1
    published_ports:
      - ansible-local:2376:2376/tcp
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      instance:
        ansible_python_interpreter: /usr/bin/python3
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
